(defun org-to-xwiki ()
  (interactive)
  (unless (equal major-mode 'org-mode)
    (error "Only use this in org-mode"))
  (let* ((filename (buffer-file-name))
         (name (file-name-nondirectory filename))
         (wiki-name (file-name-sans-extension name))
         (tmpfile (cu-join-path "/tmp" (concat wiki-name ".md")))
         (command (format "amzn-wiki.sh %s %s" tmpfile wiki-name)))
    (when (y-or-n-p (format "Run: %s" command))
      (org-export-to-file 'md tmpfile)
      (cu-send-command-to-buffer-local-terminal command))))

(provide 'init-org-to-xwiki)
