(require 'ox-md)
(defun org-get-xwiki-path()
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (re-search-forward "#\\+\\([xX][wW][iI][kK][iI]_[pP][aA][tT][hH]\\):\s*\\([-_0-9a-zA-Z/]+\\)\s*$" nil t)
    (match-string-no-properties 2)))

(defun org-open-xwiki ()
  (interactive)
  (unless (equal major-mode 'org-mode)
    (error "Only use this in org-mode"))
  (unless (equal system-type 'darwin)
    (error "Only use this in darwin"))
  (let* ((filename (buffer-file-name))
         (name (file-name-nondirectory filename))
         (wiki-path-from-property (org-get-xwiki-path))
         (wiki-url (if wiki-path-from-property
                       (format "https://w.amazon.com/bin/view/%s" wiki-path-from-property)
                     (format "https://w.amazon.com/bin/view/ApiTesting/%s/%s"
                             (cu-strip-string (shell-command-to-string "whoami") t t)
                             (file-name-sans-extension name)))))
    (shell-command (format "open %s" wiki-url))))

(defun org-to-xwiki ()
  (interactive)
  (unless (equal major-mode 'org-mode)
    (error "Only use this in org-mode"))
  (let* ((filename (buffer-file-name))
         (name (file-name-nondirectory filename))
         (wiki-path-from-property (org-get-xwiki-path))
         (wiki-name (or wiki-path-from-property (file-name-sans-extension name)))
         (tmpfile (cu-join-path "/tmp" (concat (file-name-nondirectory wiki-name) ".md")))
         (command (format "amzn-wiki-wrapper.sh %s %s %s" (if wiki-path-from-property "--no-api-testing" "")  tmpfile wiki-name)))
    (org-export-to-file 'md tmpfile)
    (when (y-or-n-p (format "Run: %s" command))
      (cu-send-command-to-buffer-local-terminal command))))

(provide 'init-org-to-xwiki)
