(add-to-list 'load-path (concat user-emacs-directory "site-lisp/dash-at-point"))
(require 'dash-at-point)
(add-to-list 'dash-at-point-mode-alist '(kotlin-mode . "kotlin"))
(add-to-list 'dash-at-point-mode-alist '(racket-mode . "racket"))
(add-to-list 'dash-at-point-mode-alist '(cmake-mode . "cmake"))
(add-to-list 'dash-at-point-mode-alist '(gradle-build-mode . "gradle"))
(add-to-list 'dash-at-point-mode-alist '(go-mode . "go"))
(provide 'init-dash)
