(topcoder-set-problem
 '((language . java)
   (statement . "return a;")
   (class-name . "TestVD")
   (method-name . "testMethod")
   (params (("double" . 1) . "a"))
   (return "double" . 1)
   (signature . "double[] testMethod(double[] a)")
   (test-cases (("{1.2, 3.4}") . "{1.2, 3.4}")
	       (("{8.2, 3.4}") . "{8.2, 3.4}")
	       (("{}") . "{}"))))
